### ISSUE TITLE
scql数据库连接问题

### ISSUE THREAD

**Issue by Jhang-Z** [byeyang/BOT#1]
你好，我在scql里的issue看到你测试了几个不同的数据库https://github.com/secretflow/scql/issues/285
我目前也想尝试将原本的mysql替换为oceanbase。
我想问一下具体需要修改下哪些文件呢
我将原本mysql的镜像替换为了oceanbase，出现你提到的connection refused问题。
我看官方回复说需要配合oceanbase proxy使用，请问具体如何操作呢，需要修改哪些文件呢？
```
oceanbase:
    image: oceanbase/oceanbase-ce
    environment:
      - MYSQL_ROOT_PASSWORD=zjigWQQt00I9l
      - TZ=Asia/Shanghai
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - mysql
      timeout: 20s
    expose:
      - "2881"
    restart: always
    volumes:
      - ./oceanbase/initdb:/docker-entrypoint-initdb.d
```
